# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.2]
    
    env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        PORT: ${{ secrets.PORT }}
        TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        SECRET: ${{ secrets.SECRET }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test and run backend
      run: |
        npm ci
        npm run lint
        npm run test
        npm run start:test &
      working-directory: backend  
    - name: Test and run frontend
      run: |
        npm ci
        npm run eslint
        npm run start &
      working-directory: frontend
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
          start: npm run test:e2e
          wait-on: http://localhost:3000
          working-directory: frontend  
